// Package postgres implements the repository contracts against the portal
// PostgreSQL database using pgx. It does not leak pgx types beyond this
// package; handlers depend on the interfaces in internal/repository.
package postgres

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/jetswu/cloudsuite/portal/backend/internal/domain"
)

// ErrNotFound is returned when a row does not exist.
var ErrNotFound = errors.New("not found")

// DomainRepo is the pgx implementation of repository.DomainRepository.
type DomainRepo struct {
	pool *pgxpool.Pool
}

// NewDomainRepo wires a DomainRepo to the given pool.
func NewDomainRepo(pool *pgxpool.Pool) *DomainRepo {
	return &DomainRepo{pool: pool}
}

const domainColumns = `id, name, tenant_id, status, stalwart_domain_id, verified_at, created_at, updated_at`

func scanDomain(row pgx.Row) (*domain.Domain, error) {
	var d domain.Domain
	err := row.Scan(
		&d.ID, &d.Name, &d.TenantID, &d.Status, &d.StalwartDomainID,
		&d.VerifiedAt, &d.CreatedAt, &d.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("scan domain: %w", err)
	}
	return &d, nil
}

// Create inserts a domain. The ID is generated by the caller (or left to the
// database default if empty).
func (r *DomainRepo) Create(ctx context.Context, d domain.Domain) error {
	_, err := r.pool.Exec(ctx, `
		INSERT INTO domains (id, name, tenant_id, status, stalwart_domain_id, verified_at)
		VALUES ($1, $2, $3, $4, $5, $6)`,
		d.ID, d.Name, d.TenantID, d.Status, d.StalwartDomainID, d.VerifiedAt,
	)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23505" {
			return fmt.Errorf("domain %q already exists: %w", d.Name, err)
		}
		return fmt.Errorf("insert domain: %w", err)
	}
	return nil
}

// GetByID fetches a domain by its UUID.
func (r *DomainRepo) GetByID(ctx context.Context, id string) (*domain.Domain, error) {
	return scanDomain(r.pool.QueryRow(ctx,
		`SELECT `+domainColumns+` FROM domains WHERE id = $1`, id))
}

// GetByName fetches a domain by its (unique) name.
func (r *DomainRepo) GetByName(ctx context.Context, name string) (*domain.Domain, error) {
	return scanDomain(r.pool.QueryRow(ctx,
		`SELECT `+domainColumns+` FROM domains WHERE name = $1`, name))
}

// List returns all domains ordered by creation time descending.
func (r *DomainRepo) List(ctx context.Context) ([]domain.Domain, error) {
	rows, err := r.pool.Query(ctx,
		`SELECT `+domainColumns+` FROM domains ORDER BY created_at DESC`)
	if err != nil {
		return nil, fmt.Errorf("list domains: %w", err)
	}
	defer rows.Close()

	out := []domain.Domain{}
	for rows.Next() {
		d, err := scanDomain(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *d)
	}
	if rows.Err() != nil {
		return nil, fmt.Errorf("iterate domains: %w", rows.Err())
	}
	return out, nil
}

// Update writes the mutable fields of a domain (status, stalwart_domain_id,
// verified_at). The updated_at timestamp is refreshed by the database trigger
// expectation; here we set it explicitly to now() for clarity.
func (r *DomainRepo) Update(ctx context.Context, d domain.Domain) error {
	tag, err := r.pool.Exec(ctx, `
		UPDATE domains
		SET name = $2, status = $3, stalwart_domain_id = $4, verified_at = $5, updated_at = now()
		WHERE id = $1`,
		d.ID, d.Name, d.Status, d.StalwartDomainID, d.VerifiedAt,
	)
	if err != nil {
		return fmt.Errorf("update domain: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// Delete removes a domain. DNS records cascade on delete.
func (r *DomainRepo) Delete(ctx context.Context, id string) error {
	tag, err := r.pool.Exec(ctx, `DELETE FROM domains WHERE id = $1`, id)
	if err != nil {
		return fmt.Errorf("delete domain: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}
